### ISSUE TITLE
Minor issues with error messages

### ISSUE THREAD

**Issue by Fryguy** [RedHatInsights/insights-api-common-rails#121]
Was reviewing some API things with @psav and we noticed a few minor oddities:

1. When you pass invalid fields (readonly for example) in a POST request, the error string that comes back has the values as symbols.  However this is strange from non-Ruby clients where symbols aren't a thing (nor or they even a thing in JSON).  These should be changed in the error message to just strings.

2. If a null value is passed to a non-nullable field the error message is strange. Something like `a, b, c: don't accept null`

cc @bdunne

**Comment by bdunne** [comment]
Do you have examples?  [We have a bunch of test cases for these responses.](https://github.com/ManageIQ/sources-api/blob/42b6081347b45958898121f39197007b8b1d23ad/spec/requests/api/v1.0/sources_spec.rb#L37-L86 Are we missing some?

**Comment by Fryguy** [comment]
Some of them are there - 

- symbols example - https://github.com/ManageIQ/sources-api/blob/42b6081347b45958898121f39197007b8b1d23ad/spec/requests/api/v1.0/sources_spec.rb#L204

- Bad grammar (singular item with "are") - https://github.com/ManageIQ/sources-api/blob/42b6081347b45958898121f39197007b8b1d23ad/spec/requests/api/v1.0/sources_spec.rb#L64

- Bad grammer ("xxx isn't match") https://github.com/ManageIQ/sources-api/blob/42b6081347b45958898121f39197007b8b1d23ad/spec/requests/api/v1.0/sources_spec.rb#L84

**Comment by mkanoor** [comment]
The bad grammar issue is coming from the openapi parser
They are all listed here
https://github.com/ota42y/openapi_parser/blob/master/lib/openapi_parser/errors.rb
Look for the message method

**Comment by bdunne** [comment]
Opened a PR to the library that raises these errors... https://github.com/ota42y/openapi_parser/pull/55

**Comment by Fryguy** [comment]
@bdunne Can this be closed now?
