### ISSUE TITLE
Sorting directive support

### ISSUE THREAD

**Issue by gmcculloug** [RedHatInsights/insights-api-common-rails#58]
Add the ability to sort properties (asc/desc).

For reference from MIQ see:
https://github.com/ManageIQ/manageiq-api/blob/8746271c320c41e2c79471336df1fce053a8c4dc/app/controllers/api/base_controller/parameters.rb#L57-L62

https://github.com/ManageIQ/manageiq-api/blob/8746271c320c41e2c79471336df1fce053a8c4dc/app/controllers/api/base_controller/parameters.rb#L78

cc @abellotti @gtanzillo

**Comment by abellotti** [comment]
With this missing in the IPP12 and the non-standard implementations out there (just reference implementations), we need to decide on the path here.

Relevant implementations we could adopt:

* sort=attr1&order=[asc|desc]
  * { :sort => "attr1", :order => "asc" | "desc" }
* sort=[asc|desc].attr1,[asc|desc].attr2,...
  * { :sort => "[asc|desc].attr1,[asc|desc].attr2,..." }
* sort_by=[+|-]attr1,[+|-]attr2,...
  * { :sort_by => "+attr1,-attr2,...." }
* sort_by[attr1]=[asc|desc]&sort_by[attr2]=[asc|desc]&....
  * { :sort_by => { "attr1" => "asc", "attr2" => "desc", ... } }

Though first one prohibit multi-column sort.

**Comment by abellotti** [comment]
This is now currently implemented:

- https://github.com/RedHatInsights/insights-api-common-rails#sorting-results
